# AI-Generated by CAFE v5.1-ACG - MIT License
.PHONY: help install test coverage format lint typecheck quality run clean velocity

help:
	@echo "Tower Climb Development Commands"
	@echo "================================"
	@echo "make install    - Install project in development mode"
	@echo "make test       - Run test suite"
	@echo "make coverage   - Run tests with coverage report"
	@echo "make format     - Format code with black"
	@echo "make lint       - Check code with flake8"
	@echo "make typecheck  - Check types with mypy"
	@echo "make quality    - Run all quality checks"
	@echo "make run        - Run the game"
	@echo "make velocity   - Check velocity tracker integration"
	@echo "make clean      - Remove build artifacts"

install:
	pip install -e ".[dev]"

test:
	pytest -v

coverage:
	pytest --cov --cov-report=html --cov-report=term

format:
	black src tests
	isort src tests

lint:
	flake8 src tests

typecheck:
	mypy src

quality: format lint typecheck test

run:
	python -m tower_climb

velocity:
	python scripts/velocity_integration.py

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
	rm -rf build dist *.egg-info
	rm -rf htmlcov .coverage .pytest_cache
	rm -rf .mypy_cache