# AI-Generated by CAFE v5.1-ACG - MIT License
"""Tests for main entry point."""

import pytest
from tower_climb.__main__ import main


def test_main_exits_cleanly():
    """Test that main function exits with status 0."""
    with pytest.raises(SystemExit) as exc_info:
        main()
    assert exc_info.value.code == 0
