# AI-Generated by CAFE v5.1-ACG - MIT License
"""Abstract base class for game states."""

from abc import ABC, abstractmethod

from tower_climb.core.window import Window


class GameState(ABC):
    """Abstract base class for game states."""

    @abstractmethod
    def enter(self) -> None:
        """Called when state becomes active."""
        pass

    @abstractmethod
    def exit(self) -> None:
        """Called when state becomes inactive."""
        pass

    @abstractmethod
    def update(self, dt: float) -> None:
        """Update state logic. dt in seconds."""
        pass

    @abstractmethod
    def draw(self, window: Window) -> None:
        """Draw state to window."""
        pass
