#!/usr/bin/env python3
# AI-Generated by CAFE v5.1-ACG - MIT License
"""Add a regeneration to current contract."""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

from scripts.velocity_integration import get_tracker


def add_regeneration(contract_id: str, reason: str):
    """Add regeneration to contract."""
    tracker = get_tracker()
    
    try:
        tracker.add_regeneration(contract_id, reason)
        print(f"[OK] Regeneration added to {contract_id}")
        print(f"[INFO] Reason: {reason}")
    except Exception as e:
        print(f"[ERROR] Failed to add regeneration: {e}")
        return 1
    
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python add_regeneration.py <CONTRACT_ID> <REASON>")
        print("Example: python add_regeneration.py P0-S1-C1 'Fixed mock return value'")
        sys.exit(1)
    
    contract_id = sys.argv[1]
    reason = " ".join(sys.argv[2:])
    sys.exit(add_regeneration(contract_id, reason))