#!/usr/bin/env python3
# AI-Generated by CAFE v5.1-ACG - MIT License
"""Complete tracking for a contract."""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

from scripts.velocity_integration import get_tracker


def complete_contract(contract_id: str, coverage: float):
    """Complete contract tracking."""
    tracker = get_tracker()
    
    print(f"[INFO] Completing contract: {contract_id}")
    
    try:
        result = tracker.complete_contract(contract_id, coverage=coverage)
        print(f"[OK] Contract {contract_id} completed")
        print(f"[INFO] Duration: {result['duration_minutes']:.2f} minutes")
        print(f"[INFO] Regenerations: {result['regenerations']}")
        print(f"[INFO] Coverage: {coverage}%")
        
    except Exception as e:
        print(f"[ERROR] Failed to complete contract: {e}")
        return 1
    
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python complete_contract.py <CONTRACT_ID> <COVERAGE>")
        print("Example: python complete_contract.py P0-S1-C1 95.5")
        sys.exit(1)
    
    contract_id = sys.argv[1]
    coverage = float(sys.argv[2])
    sys.exit(complete_contract(contract_id, coverage))