#!/usr/bin/env python3
# AI-Generated by CAFE v5.1-ACG - MIT License
"""Start tracking a new contract with velocity tracker."""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

from scripts.velocity_integration import get_tracker


def start_contract(contract_id: str):
    """Start tracking a contract."""
    tracker = get_tracker()
    
    print(f"[INFO] Starting contract: {contract_id}")
    
    try:
        tracker.start_contract(contract_id)
        print(f"[OK] Contract {contract_id} tracking started")
        print(f"[INFO] Session: {tracker.session.session_id}")
        
        # Show current status
        report = tracker.generate_report()
        if report and "summary" in report:
            summary = report["summary"]
            print(f"\n[INFO] Active Contracts: {summary.get('in_progress', 0)}")
            print(f"[INFO] Total Contracts: {summary.get('total_contracts', 0)}")
            
    except Exception as e:
        print(f"[ERROR] Failed to start contract: {e}")
        return 1
    
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python start_contract.py <CONTRACT_ID>")
        print("Example: python start_contract.py P0-S1-C1")
        sys.exit(1)
    
    sys.exit(start_contract(sys.argv[1]))