#!/usr/bin/env python3
# AI-Generated by CAFE v5.1-ACG - MIT License
"""Manual test for window creation."""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent / "src"))

from tower_climb.core.window import Window


def test_window():
    """Test window creation and basic loop."""
    print("[INFO] Creating window...")
    window = Window()
    
    try:
        window.initialize()
        print("[OK] Window created successfully")
        print("[INFO] Press X to close window")
        
        # Basic game loop
        clock = pygame.time.Clock()
        while window.is_running:
            # Handle events
            if not window.handle_events():
                break
                
            # Clear screen
            window.clear((64, 64, 64))  # Dark gray
            
            # Present frame
            window.present()
            
            # Cap at 60 FPS
            clock.tick(60)
            
    except Exception as e:
        print(f"[ERROR] {e}")
        return 1
    finally:
        window.quit()
        print("[INFO] Window closed")
        
    return 0


if __name__ == "__main__":
    import pygame
    sys.exit(test_window())