# AI-Generated by CAFE v5.1-ACG - CC BY-NC 4.0 License
"""Tower Climb - A roguelike tower climbing game."""

__version__ = "0.1.4"
__author__ = "Aeturnis Development Labs"
__license__ = "CC BY-NC 4.0"
